const { describe, it, expect } = require('bun:test');
const fs = require('fs');
const path = require('path');

function readSharedStyles() {
    const filePath = path.resolve(__dirname, '../../../gui/src/shared/styles.css');
    return fs.readFileSync(filePath, 'utf8');
}

function readCssBlock(cssText, selector) {
    const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const blockPattern = new RegExp(`(?:^|\\n)\\s*${escapedSelector}\\s*\\{([\\s\\S]*?)\\}`, 'm');
    const match = cssText.match(blockPattern);
    return match ? match[1] : '';
}

describe('GUI shared styles behavior', () => {
    it('uses mode-specific gui size tokens for row visuals and typography', () => {
        const cssText = readSharedStyles();
        const pageBlock = readCssBlock(cssText, 'html, body');
        const rootBlock = readCssBlock(cssText, ':root');
        const overlayShellBlock = readCssBlock(cssText, '.gui-shell--overlay');
        const dockShellBlock = readCssBlock(cssText, '.gui-shell--dock');
        const overlayExitBlock = readCssBlock(cssText, '.gui-row--overlay-exit');
        const rowBlock = readCssBlock(cssText, '.gui-row');
        const paypiggyRowBlock = readCssBlock(cssText, '.gui-row--paypiggy');
        const paypiggyUsernameBlock = readCssBlock(cssText, '.gui-row--paypiggy .gui-row__username');
        const paypiggyTextBlock = readCssBlock(cssText, '.gui-row--paypiggy .gui-row__text');
        const memberChatRowBlock = readCssBlock(cssText, '.gui-row--member-chat');
        const overlayEnterBlock = readCssBlock(cssText, '.gui-row--overlay-enter');
        const avatarBlock = readCssBlock(cssText, '.gui-row__avatar');
        const platformIconBlock = readCssBlock(cssText, '.gui-row__platform-icon');
        const usernameBlock = readCssBlock(cssText, '.gui-row__username');
        const memberTagBlock = readCssBlock(cssText, '.gui-row__member-tag');
        const badgesBlock = readCssBlock(cssText, '.gui-row__badges');
        const badgeBlock = readCssBlock(cssText, '.gui-row__badge');
        const textBlock = readCssBlock(cssText, '.gui-row__text');
        const memberContentBlock = readCssBlock(cssText, '.gui-row__content--member-chat');
        const memberHeaderBlock = readCssBlock(cssText, '.gui-row__header--member-chat');
        const memberUsernameBlock = readCssBlock(cssText, '.gui-row__username--member-chat');
        const memberTextBlock = readCssBlock(cssText, '.gui-row__text--member-chat');
        const memberImageClipBlock = readCssBlock(cssText, '.gui-row__member-image-clip');
        const memberImageBlock = readCssBlock(cssText, '.gui-row__member-image');
        const emoteBlock = readCssBlock(cssText, '.gui-row__emote');

        expect(pageBlock).toContain('margin: 0;');
        expect(pageBlock).toContain('padding: 0;');
        expect(rootBlock).toContain('--gui-row-background-opacity: 0.95;');
        expect(rootBlock).toContain('--gui-overlay-avatar-size: 75px;');
        expect(rootBlock).toContain('--gui-overlay-platform-icon-size: 30px;');
        expect(rootBlock).toContain('--gui-overlay-badge-size: 18px;');
        expect(rootBlock).toContain('--gui-overlay-row-header-font-size: 20px;');
        expect(rootBlock).toContain('--gui-overlay-row-body-font-size: 23px;');
        expect(rootBlock).toContain('--gui-overlay-emote-size: 50px;');
        expect(rootBlock).toContain('--gui-dock-avatar-size: 48px;');
        expect(rootBlock).toContain('--gui-dock-platform-icon-size: 24px;');
        expect(rootBlock).toContain('--gui-dock-badge-size: 14px;');
        expect(rootBlock).toContain('--gui-dock-row-header-font-size: 16px;');
        expect(rootBlock).toContain('--gui-dock-row-body-font-size: 18px;');
        expect(rootBlock).toContain('--gui-dock-emote-size: 36px;');
        expect(rootBlock).toContain('--gui-monetization-notification-background: rgba(204, 170, 0, var(--gui-row-background-opacity));');
        expect(overlayShellBlock).toContain('height: 100vh;');
        expect(overlayShellBlock).toContain('overflow: hidden;');
        expect(overlayShellBlock).toContain('--gui-avatar-size-current: var(--gui-overlay-avatar-size);');
        expect(overlayShellBlock).toContain('--gui-platform-icon-size-current: var(--gui-overlay-platform-icon-size);');
        expect(overlayShellBlock).toContain('--gui-badge-size-current: var(--gui-overlay-badge-size);');
        expect(overlayShellBlock).toContain('--gui-row-header-font-size-current: var(--gui-overlay-row-header-font-size);');
        expect(overlayShellBlock).toContain('--gui-row-body-font-size-current: var(--gui-overlay-row-body-font-size);');
        expect(overlayShellBlock).toContain('--gui-emote-size-current: var(--gui-overlay-emote-size);');
        expect(dockShellBlock).toContain('min-height: 100vh;');
        expect(dockShellBlock).toContain('background: linear-gradient(180deg, #1a1f26 0%, #12161c 100%);');
        expect(dockShellBlock).toContain('--gui-avatar-size-current: var(--gui-dock-avatar-size);');
        expect(dockShellBlock).toContain('--gui-platform-icon-size-current: var(--gui-dock-platform-icon-size);');
        expect(dockShellBlock).toContain('--gui-badge-size-current: var(--gui-dock-badge-size);');
        expect(dockShellBlock).toContain('--gui-row-header-font-size-current: var(--gui-dock-row-header-font-size);');
        expect(dockShellBlock).toContain('--gui-row-body-font-size-current: var(--gui-dock-row-body-font-size);');
        expect(dockShellBlock).toContain('--gui-emote-size-current: var(--gui-dock-emote-size);');
        expect(overlayExitBlock).toContain('position: absolute;');
        expect(overlayExitBlock).toContain('animation: gui-overlay-row-exit 1000ms ease-out forwards;');
        expect(cssText).toContain('@keyframes gui-overlay-row-exit');
        expect(cssText).toContain('translateY(calc(-1 * var(--overlay-exit-travel, 0px)))');
        expect(rowBlock).toContain('grid-template-columns: auto 1fr;');
        expect(rowBlock).toContain('background: rgba(0, 0, 0, var(--gui-row-background-opacity));');
        expect(paypiggyRowBlock).toContain('background: rgba(15, 157, 88, var(--gui-row-background-opacity));');
        expect(cssText).toContain('.gui-row[data-row-type="platform:gift"],');
        expect(cssText).toContain('.gui-row[data-row-type="platform:giftpaypiggy"],');
        expect(cssText).toContain('.gui-row[data-row-type="platform:paypiggy"],');
        expect(cssText).toContain('.gui-row[data-row-type="platform:envelope"] {');
        expect(cssText).toContain('background: var(--gui-monetization-notification-background);');
        expect(paypiggyUsernameBlock).toContain('color: #ffffff;');
        expect(paypiggyTextBlock).toContain('color: #ffffff;');
        expect(memberChatRowBlock).not.toContain('padding-bottom: 0;');
        expect(overlayEnterBlock).toContain('animation: none;');
        expect(avatarBlock).toContain('width: var(--gui-avatar-size-current);');
        expect(avatarBlock).toContain('height: var(--gui-avatar-size-current);');
        expect(platformIconBlock).toContain('width: var(--gui-platform-icon-size-current);');
        expect(platformIconBlock).toContain('height: var(--gui-platform-icon-size-current);');
        expect(platformIconBlock).toContain('transform: translateY(1px);');
        expect(usernameBlock).toContain('font-size: var(--gui-row-header-font-size-current);');
        expect(memberTagBlock).toContain('font-size: calc(var(--gui-row-header-font-size-current) * 0.65 * 1.15);');
        expect(memberTagBlock).toContain('color: gold;');
        expect(memberTagBlock).toContain('display: inline-flex;');
        expect(memberTagBlock).toContain('align-items: center;');
        expect(badgesBlock).toContain('display: inline-flex;');
        expect(badgesBlock).toContain('align-items: center;');
        expect(badgeBlock).toContain('width: var(--gui-badge-size-current);');
        expect(badgeBlock).toContain('height: var(--gui-badge-size-current);');
        expect(textBlock).toContain('font-size: var(--gui-row-body-font-size-current);');
        expect(memberContentBlock).toContain('display: flow-root;');
        expect(memberHeaderBlock).toContain('min-width: 0;');
        expect(memberUsernameBlock).toContain('min-width: 0;');
        expect(memberUsernameBlock).toContain('overflow: hidden;');
        expect(memberUsernameBlock).toContain('text-overflow: ellipsis;');
        expect(memberUsernameBlock).toContain('white-space: nowrap;');
        expect(memberUsernameBlock).toContain('flex: 0 1 auto;');
        expect(memberTextBlock).toContain('display: block;');
        expect(memberTextBlock).toContain('overflow-wrap: anywhere;');
        expect(memberTextBlock).toContain('word-break: break-word;');
        expect(memberImageClipBlock).toContain('width: 120px;');
        expect(memberImageClipBlock).toContain('height: 110px;');
        expect(memberImageClipBlock).toContain('float: right;');
        expect(memberImageClipBlock).toContain('margin-left: 10px;');
        expect(memberImageClipBlock).toContain('margin-right: -80px;');
        expect(memberImageClipBlock).toContain('margin-top: -40px;');
        expect(memberImageClipBlock).toContain('margin-bottom: 0;');
        expect(memberImageClipBlock).toContain('overflow: hidden;');
        expect(memberImageBlock).toContain('width: 120px;');
        expect(memberImageBlock).toContain('height: 120px;');
        expect(memberImageBlock).toContain('object-fit: contain;');
        expect(emoteBlock).toContain('width: var(--gui-emote-size-current);');
        expect(emoteBlock).toContain('height: var(--gui-emote-size-current);');
    });
});
